# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Release SvelteSimpleIcons

on:
  push:
    branches:
      - main
  release:
    types: [created]

env:
  PNPM_VERSION: 9.15.0

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          registry-url: https://registry.npmjs.org/

      - name: 🔥 Installing pnpm
        run: |
          corepack enable
          corepack prepare pnpm@${{ env.PNPM_VERSION }} --activate

      - name: 📦 Install Dependencies
        run: |
          pnpm --version && pnpm install --frozen-lockfile
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔥 Run generate:icons
        run: pnpm run generate:icons

      - name: 💣 Run build
        run: pnpm run build

      # - name: Delete tags
      #   run: |
      #     git tag | xargs git tag -d

      - name: Create Release Pull Request or Publish to GitHub Packages 📦
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: "ci(Release): version icons-pack/react-simple-icons"
          title: "ci(Release): version icons-pack/react-simple-icons"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
